// SOURCE OF TRUTH: Dev 1's "reference packet" message.
// This file should already exist on dev1-foundation at this exact path once
// you pull. It is copied here verbatim (not modified) purely so this
// standalone package type-checks on its own before you merge it in.
//
// Do NOT edit this file once you've pulled the real one from Dev 1 — if
// there's ever a mismatch, take Dev 1's version, not this copy.

export type UserRole = 'PI' | 'COORDINATOR' | 'NPVCC_OFFICER' | 'ADMIN' | 'ETHICS_COMMITTEE' | 'MONITOR'
export type StudyPhase = 'PHASE_1' | 'PHASE_2' | 'PHASE_3' | 'PHASE_4' | 'OBSERVATIONAL'
export type StudyType = 'INTERVENTIONAL' | 'OBSERVATIONAL'
export type MonitoringFrequency = 'DAILY' | 'WEEKLY' | 'FORTNIGHTLY' | 'MONTHLY' | 'CUSTOM'

export type PrakritiType = 'VATA' | 'PITTA' | 'KAPHA' | 'VATA_PITTA' | 'PITTA_KAPHA' | 'VATA_KAPHA' | 'SAMADOSHA'
export type AgniType = 'SAMAGNI' | 'TIKSHNAGNI' | 'MANDAGNI' | 'VISHAMAGNI'

export type AssessmentStatus = 'DUE' | 'COMPLETED' | 'OVERDUE' | 'NOT_APPLICABLE'
export type InterventionType = 'DRUG' | 'PATHYA' | 'ANUPANA' | 'LIFESTYLE'
export type CriterionType = 'INCLUSION' | 'EXCLUSION'
export type CriteriaResult = 'PASS' | 'FAIL' | 'NOT_ASSESSED'
